export const locations = [
  "Israel",
  "USA - New Jersey - 1",
  "USA - New Jersey - 3",
  "USA - New York",
  "USA - Atlanta",
  "USA - Tampa - 1",
  "USA - Miami - 2",
  "USA - Mami",
  "USA - Washington DC",
  "USA - Dallas",
  "USA - Houston",
  "USA - Denver",
  "USA - Chicago",
  "USA - Lincoln Park",
  "USA - Albuquerque",
  "USA - San Francisco",
  "USA - Los Angeles - 3",
  "USA - Los Angeles - 2",
  "USA - Seattle",
  "USA - Salt Lake City",
  "USA - Phoenix",
  "USA - New Jersey - 2",
  "USA - Los Angeles - 1",
  "USA - Los Angeles - 5",
  "USA - Santa Monica",
  "UK - London",
  "UK - Docklands",
  "UK - East London",
  "UK - Midlands",
  "France - Paris - 2",
  "France - Strasbourg",
  "Netherlands - Amsterdam",
  "Netherlands - Rotterdam",
  "Netherlands - The Hague",
  "Lebanon",
  "Egypt",
  "Turkey",
  "Algeria",
  "Italy - Cosenza",
  "Italy - Naples",
  "Canada - Toronto",
  "Canada - Toronto - 2",
  "Germany - Frankfurt - 3",
  "Germany - Nuremberg",
  "Germany - Frankfurt - 1",
  "Sweden",
  "Sweden - 2",
  "Switzerland",
  "Switzerland - 2",
  "Romania",
  "Isle of Man",
  "Spain - Madrid",
  "Spain - Barelona",
  "Spain - Barcelona - 2",
  "Ireland",
  "Iceland",
  "Norway",
  "Denmark",
  "Belgium",
  "Finland",
  "Greece",
  "Portugal",
  "Austria",
  "Armenia",
  "Poland",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Czech Republic",
  "Andorra",
  "Montenegro",
  "Bosnia and Herzegovina",
  "Luxembourg",
  "Hungary",
  "Bulgaria",
  "Belarus",
  "Ukraine",
  "Malta",
  "Liechtenstein",
  "Cyprus",
  "Albania",
  "Croatia",
  "Slovakia",
  "Monaco",
  "Jersey",
  "North Macedonia",
  "Moldova",
  "Serbia",
  "Georgia",
  "Singapore - Jurong",
  "Singapore - CBD",
  "Singapore - Marina Bay",
  "Hong Kong - 1",
  "Hong Kong - 2",
  "Japan - Tokyo",
  "Japan - Shibuya",
  "Japan - Yokohama",
  "Japan - Osaka",
  "Australia - Melbourne",
  "Australia - Woolloomooloo",
  "Australia - Sydney",
  "Australia - Perth",
  "Australia - Brisbane",
  "Australia - Adelaide",
  "Australia - Sydney - 2",
  "South Korea - 2",
  "Philippines",
  "Malaysia",
  "India (via UK)",
  "Sri Lanka",
  "Pakistan",
  "Kazakhstan",
  "Thailand",
  "Indonesia",
  "New Zealand",
  "Taiwan - 3",
  "Vietnam",
  "Macau",
  "Cambodia",
  "Mongolia",
  "Laos",
  "Myanmar",
  "Nepal",
  "Guam",
  "Uzbekistan",
  "Bangladesh",
  "Bhutan",
  "Brunei",
  "Mexico",
  "Brazil - 2",
  "Brazil",
  "Panama",
  "Chile",
  "Argentina",
  "Bolivia",
  "Costa Rica",
  "Colombia",
  "Venezuela",
  "Ecuador",
  "Guatemala",
  "Peru",
  "Uruguay",
  "Behamas",
  "Dominican Republic",
  "Jamaica",
  "Puerto Rico",
  "Bermuda",
  "Tinidad and Tobago",
  "Cayman Islands",
  "Cuba",
  "Honduras",
  "Ghana",
  "Morocco",
  "South Africa",
  "Kenya",
];
