export const locations = [
  //{ name: "Israel" },
  //{ name: "USA - Miami - 2" },
  //{ name: "USA - Miami" },
  //{ name: "USA - Atlanta" },
  //{ name: "USA - New Jersey - 3" },
  //{ name: "USA - New Jersey - 1" },
  //{ name: "USA - New York" },
  //{ name: "USA - Tampa - 1" },
  //{ name: "USA - Washington DC" },
  //{ name: "USA - Dallas" },
  //{ name: "USA - Houston" },
  //{ name: "USA - Denver" },
  //{ name: "USA - Chicago" },
  { name: "USA - Lincoln Park" },
  { name: "USA - Albuquerque" },
  //{ name: "USA - San Francisco" },
 // { name: "USA - Los Angeles - 3" },
  //{ name: "USA - Los Angeles - 2" },
  //{ name: "USA - Seattle" },
  { name: "USA - Salt Lake City" },
  //{ name: "USA - Phoenix" },
  { name: "USA - New Jersey - 2" },
  //{ name: "USA - Los Angeles - 1" },
  { name: "USA - Los Angeles - 5" },
  { name: "USA - Santa Monica" },
  { name: "UK - London" },
  //{ name: "UK - Docklands" },
  //{ name: "UK - East London" },
  { name: "UK - Midlands" },
  //{ name: "France - Paris - 2" },
  //{ name: "France - Strasbourg" },
  //{ name: "Netherlands - Amsterdam" },
  //{ name: "Netherlands - Rotterdam" },
  //{ name: "Netherlands - The Hague" },
  //{ name: "Lebanon" },
  //{ name: "Egypt" },
  //{ name: "Turkey" },
  //{ name: "Algeria" },
  //{ name: "Italy - Cosenza" },
  //{ name: "Italy - Naples" },
  //{ name: "Canada - Toronto" },
  { name: "Canada - Toronto - 2" },
 // { name: "Germany - Frankfurt - 3" },
 // { name: "Germany - Nuremberg" },
  //{ name: "Germany - Frankfurt - 1" },
  //{ name: "Sweden" },
  { name: "Sweden - 2" },
  //{ name: "Switzerland" },
  { name: "Switzerland - 2" },
  //{ name: "Romania" },
  { name: "Isle of Man" },
  //{ name: "Spain - Madrid" },
  //{ name: "Spain - Barelona" },
  //{ name: "Spain - Barcelona - 2" },
  //{ name: "Bulgaria" },
  //{ name: "Ireland" },
  { name: "Iceland" },
  { name: "Norway" },
  { name: "Denmark" },
  //{ name: "Belgium" },
  { name: "Finland" },
  { name: "Greece" },
  { name: "Portugal" },
  { name: "Austria" },
  { name: "Armenia" },
  //{ name: "Poland" },
  { name: "Lithuania" },
  { name: "Latvia" },
  { name: "Estonia" },
  //{ name: "Czech Republic" },
  { name: "Andorra" },
  { name: "Montenegro" },
  { name: "Bosnia and Herzegovina" },
  { name: "Luxembourg" },
  { name: "Hungary" },
  { name: "Belarus" },
  { name: "Ukraine" },
  { name: "Malta" },
  { name: "Liechtenstein" },
  { name: "Cyprus" },
  { name: "Albania" },
  { name: "Croatia" },
  { name: "Slovakia" },
  { name: "Monaco" },
  { name: "Jersey" },
  { name: "North Macedonia" },
  { name: "Moldova" },
  { name: "Serbia" },
  { name: "Georgia" },
  { name: "Singapore - Jurong" },
  { name: "Singapore - CBD" },
  { name: "Singapore - Marina Bay" },
  { name: "Hong Kong - 1" },
  { name: "Hong Kong - 2" },
  { name: "Japan - Tokyo" },
  { name: "Japan - Shibuya" },
  { name: "Japan - Yokohama" },
  { name: "Japan - Osaka" },
  { name: "Australia - Melbourne" },
  { name: "Australia - Woolloomooloo" },
  { name: "Australia - Sydney" },
  { name: "Australia - Perth" },
  { name: "Australia - Brisbane" },
  { name: "Australia - Adelaide" },
  { name: "Australia - Sydney - 2" },
  { name: "South Korea - 2" },
  { name: "Philippines" },
  { name: "Malaysia" },
  { name: "India (via UK)" },
  { name: "Sri Lanka" },
  { name: "Pakistan" },
  { name: "Kazakhstan" },
  { name: "Thailand" },
  { name: "Indonesia" },
  { name: "New Zealand" },
  { name: "Taiwan - 3" },
  { name: "Vietnam" },
  { name: "Macau" },
  { name: "Cambodia" },
  { name: "Mongolia" },
  { name: "Laos" },
  { name: "Myanmar" },
  { name: "Nepal" },
  { name: "Guam" },
  { name: "Uzbekistan" },
  { name: "Bangladesh" },
  { name: "Bhutan" },
  { name: "Brunei" },
  { name: "Mexico" },
  { name: "Brazil - 2" },
  { name: "Brazil" },
  { name: "Panama" },
  { name: "Chile" },
  { name: "Argentina" },
  { name: "Bolivia" },
  { name: "Costa Rica" },
  { name: "Colombia" },
  { name: "Venezuela" },
  { name: "Ecuador" },
  { name: "Guatemala" },
  { name: "Peru" },
  { name: "Uruguay" },
  { name: "Behamas" },
  { name: "Dominican Republic" },
  { name: "Jamaica" },
  { name: "Puerto Rico" },
  { name: "Bermuda" },
  { name: "Tinidad and Tobago" },
  { name: "Cayman Islands" },
  { name: "Cuba" },
  { name: "Honduras" },
  { name: "Ghana" },
  { name: "Morocco" },
  { name: "South Africa" },
  { name: "Kenya" },
];
