export const locations = [
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Albania",
    region: "Europe",
    city: "Tirana",
    categories: ["Standard VPN servers"],
    number: 36,
    hostname: "al36.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["87.120.102.3"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Algeria",
    region: "Africa the Middle East and India",
    city: "Algiers",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "dz1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.137.76.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Andorra",
    region: "Europe",
    city: "Andorra la Vella",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ad1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.137.77.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Argentina",
    region: "The Americas",
    city: "Buenos Aires",
    categories: ["Standard VPN servers", "P2P"],
    number: 50,
    hostname: "ar50.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.50.33.48"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Armenia",
    region: "Europe",
    city: "Yerevan",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "am1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.137.78.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Australia",
    region: "Asia Pacific",
    city: "Adelaide",
    categories: ["Standard VPN servers", "P2P"],
    number: 638,
    hostname: "au638.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["116.90.72.43"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Australia",
    region: "Asia Pacific",
    city: "Brisbane",
    categories: ["Standard VPN servers", "P2P"],
    number: 585,
    hostname: "au585.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.137.12.179"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Australia",
    region: "Asia Pacific",
    city: "Melbourne",
    categories: ["Standard VPN servers", "P2P"],
    number: 569,
    hostname: "au569.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.137.14.147"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Australia",
    region: "Asia Pacific",
    city: "Perth",
    categories: ["Standard VPN servers", "P2P"],
    number: 599,
    hostname: "au599.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.107.196.131"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Australia",
    region: "Asia Pacific",
    city: "Sydney",
    categories: ["Standard VPN servers", "P2P"],
    number: 529,
    hostname: "au529.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.1.212.91"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Austria",
    region: "Europe",
    city: "Vienna",
    categories: ["Standard VPN servers", "P2P"],
    number: 80,
    hostname: "at80.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["5.253.207.203"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Azerbaijan",
    region: "Europe",
    city: "Baku",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "az1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.137.79.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bahamas",
    region: "The Americas",
    city: "Nassau",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bs1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.95.160.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bangladesh",
    region: "Asia Pacific",
    city: "Dhaka",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bd1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.95.161.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Belgium",
    region: "Europe",
    city: "Brussels",
    categories: ["Standard VPN servers", "P2P"],
    number: 148,
    hostname: "be148.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.102.19.137"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Belize",
    region: "The Americas",
    city: "Belmopan",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bz1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.95.162.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bermuda",
    region: "The Americas",
    city: "Hamilton",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bm1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.95.163.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bhutan",
    region: "Asia Pacific",
    city: "Thimphu",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bt1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.134.188.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bolivia",
    region: "The Americas",
    city: "La Paz",
    categories: ["Standard VPN servers"],
    number: 1,
    hostname: "bo1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.134.189.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bosnia and Herzegovina",
    region: "Europe",
    city: "Sarajevo",
    categories: ["Standard VPN servers", "P2P"],
    number: 12,
    hostname: "ba12.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.212.111.183"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Brazil",
    region: "The Americas",
    city: "Sao Paulo",
    categories: ["Standard VPN servers", "P2P"],
    number: 71,
    hostname: "br71.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["189.1.170.129"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Brunei Darussalam",
    region: "Asia Pacific",
    city: "Bandar Seri Begawan",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "bn1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.134.190.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Bulgaria",
    region: "Europe",
    city: "Sofia",
    categories: ["Standard VPN servers", "P2P"],
    number: 38,
    hostname: "bg38.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["217.138.202.147"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Cambodia",
    region: "Asia Pacific",
    city: "Phnom Penh",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "kh1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["45.134.191.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Canada",
    region: "The Americas",
    city: "Montreal",
    categories: ["Standard VPN servers", "P2P"],
    number: 1066,
    hostname: "ca1066.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["86.106.90.243"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Canada",
    region: "The Americas",
    city: "Toronto",
    categories: ["Double VPN"],
    number: 74,
    hostname: "us-ca74.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["176.113.72.83"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Canada",
    region: "The Americas",
    city: "Vancouver",
    categories: ["Standard VPN servers", "P2P"],
    number: 1566,
    hostname: "ca1566.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.153.179.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Cayman Islands",
    region: "The Americas",
    city: "George Town",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ky1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["95.214.112.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Chile",
    region: "The Americas",
    city: "Santiago",
    categories: ["Standard VPN servers", "P2P"],
    number: 33,
    hostname: "cl33.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["85.190.229.4"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Colombia",
    region: "The Americas",
    city: "Bogota",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "co1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.216.73.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Costa Rica",
    region: "The Americas",
    city: "San Jose",
    categories: ["Standard VPN servers"],
    number: 36,
    hostname: "cr36.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["179.48.249.195"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Croatia",
    region: "Europe",
    city: "Zagreb",
    categories: ["Standard VPN servers", "P2P"],
    number: 33,
    hostname: "hr33.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.160.118.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Cyprus",
    region: "Europe",
    city: "Nicosia",
    categories: ["Standard VPN servers", "P2P"],
    number: 30,
    hostname: "cy30.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.19.204.161"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Czech Republic",
    region: "Europe",
    city: "Prague",
    categories: ["Standard VPN servers", "P2P"],
    number: 93,
    hostname: "cz93.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["217.138.199.27"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Denmark",
    region: "Europe",
    city: "Copenhagen",
    categories: ["Standard VPN servers", "P2P"],
    number: 150,
    hostname: "dk150.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.194.3"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Dominican Republic",
    region: "The Americas",
    city: "Santo Domingo",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "do1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["95.214.113.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Ecuador",
    region: "The Americas",
    city: "Quito",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ec1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["95.214.114.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Egypt",
    region: "Africa the Middle East and India",
    city: "Cairo",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "eg1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.66.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "El Salvador",
    region: "The Americas",
    city: "San Salvador",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "sv1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["95.214.115.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Estonia",
    region: "Europe",
    city: "Tallinn",
    categories: ["Standard VPN servers", "P2P"],
    number: 64,
    hostname: "ee64.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["85.190.239.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Finland",
    region: "Europe",
    city: "Helsinki",
    categories: ["Standard VPN servers", "P2P"],
    number: 179,
    hostname: "fi179.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["85.202.81.124"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "France",
    region: "Europe",
    city: "Marseille",
    categories: ["Standard VPN servers", "P2P"],
    number: 789,
    hostname: "fr789.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["138.199.16.7"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "France",
    region: "Europe",
    city: "Paris",
    categories: ["Double VPN"],
    number: 10,
    hostname: "uk-fr10.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["89.35.30.163"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Georgia",
    region: "Europe",
    city: "Tbilisi",
    categories: ["Standard VPN servers", "P2P"],
    number: 13,
    hostname: "ge13.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["81.17.123.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Germany",
    region: "Europe",
    city: "Berlin",
    categories: ["Standard VPN servers", "P2P"],
    number: 1069,
    hostname: "de1069.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["194.233.96.10"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Germany",
    region: "Europe",
    city: "Frankfurt",
    categories: ["Dedicated IP"],
    number: 507,
    hostname: "de507.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.130.184.115"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Ghana",
    region: "Africa the Middle East and India",
    city: "Accra",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "gh1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["176.53.176.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Greece",
    region: "Europe",
    city: "Athens",
    categories: ["Standard VPN servers", "P2P"],
    number: 47,
    hostname: "gr47.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["178.132.104.2"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Greenland",
    region: "The Americas",
    city: "Nuuk",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "gl1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["176.53.177.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Guam",
    region: "Asia Pacific",
    city: "Hagatna",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "gu1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["176.53.178.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Guatemala",
    region: "The Americas",
    city: "Guatemala City",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "gt1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["176.53.179.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Honduras",
    region: "The Americas",
    city: "Tegucigalpa",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "hn1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.9.32.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Hong Kong",
    region: "Asia Pacific",
    city: "Hong Kong",
    categories: ["Double VPN"],
    number: 7,
    hostname: "tw-hk7.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.213.82.114"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Hungary",
    region: "Europe",
    city: "Budapest",
    categories: ["Standard VPN servers", "P2P"],
    number: 47,
    hostname: "hu47.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["217.138.192.99"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Iceland",
    region: "Europe",
    city: "Reykjavik",
    categories: ["Standard VPN servers", "P2P"],
    number: 63,
    hostname: "is63.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.234.68.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "India",
    region: "Africa the Middle East and India",
    city: "Mumbai",
    categories: ["Standard VPN servers", "P2P"],
    number: 140,
    hostname: "in140.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["81.17.122.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Indonesia",
    region: "Asia Pacific",
    city: "Jakarta",
    categories: ["Standard VPN servers", "P2P"],
    number: 46,
    hostname: "id46.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.213.83.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Ireland",
    region: "Europe",
    city: "Dublin",
    categories: ["Standard VPN servers", "P2P"],
    number: 83,
    hostname: "ie83.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["84.247.48.83"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Isle of Man",
    region: "Europe",
    city: "Douglas",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "im1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.9.33.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Israel",
    region: "Africa the Middle East and India",
    city: "Tel Aviv",
    categories: ["Standard VPN servers", "P2P"],
    number: 58,
    hostname: "il58.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["169.150.226.21"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Italy",
    region: "Europe",
    city: "Milan",
    categories: ["Standard VPN servers", "P2P"],
    number: 132,
    hostname: "it132.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["217.138.197.75"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Italy",
    region: "Europe",
    city: "Rome",
    categories: ["Standard VPN servers", "P2P"],
    number: 250,
    hostname: "it250.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["85.190.232.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Jamaica",
    region: "The Americas",
    city: "Kingston",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "jm1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.9.34.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Japan",
    region: "Asia Pacific",
    city: "Osaka",
    categories: ["Standard VPN servers", "P2P"],
    number: 632,
    hostname: "jp632.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["192.166.247.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Japan",
    region: "Asia Pacific",
    city: "Tokyo",
    categories: ["Standard VPN servers", "P2P"],
    number: 429,
    hostname: "jp429.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.210.107"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Jersey",
    region: "Europe",
    city: "Saint Helier",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "je1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.9.35.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Kazakhstan",
    region: "Asia Pacific",
    city: "Astana",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "kz1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.69.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Kenya",
    region: "Africa the Middle East and India",
    city: "Nairobi",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ke1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.68.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Lao People's Democratic Republic",
    region: "Asia Pacific",
    city: "Vientiane",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "la1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.227.132.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Latvia",
    region: "Europe",
    city: "Riga",
    categories: ["Standard VPN servers", "P2P"],
    number: 44,
    hostname: "lv44.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["196.240.54.3"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Lebanon",
    region: "Africa the Middle East and India",
    city: "Beirut",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "lb1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.227.133.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Liechtenstein",
    region: "Europe",
    city: "Vaduz",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "li1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.70.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Lithuania",
    region: "Europe",
    city: "Vilnius",
    categories: ["Standard VPN servers", "P2P"],
    number: 7,
    hostname: "lt7.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.65.50.11"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Luxembourg",
    region: "Europe",
    city: "Luxembourg",
    categories: ["Standard VPN servers", "P2P"],
    number: 102,
    hostname: "lu102.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["194.110.85.0"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Malaysia",
    region: "Asia Pacific",
    city: "Kuala Lumpur",
    categories: ["Standard VPN servers", "P2P"],
    number: 49,
    hostname: "my49.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["193.36.237.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Malta",
    region: "Europe",
    city: "Valletta",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "mt1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.80.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Mexico",
    region: "The Americas",
    city: "Mexico",
    categories: ["Standard VPN servers", "P2P"],
    number: 50,
    hostname: "mx50.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["192.154.196.11"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Moldova",
    region: "Europe",
    city: "Chisinau",
    categories: ["Standard VPN servers"],
    number: 19,
    hostname: "md19.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["178.175.141.209"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Monaco",
    region: "Europe",
    city: "Monte Carlo",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "mc1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.81.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Mongolia",
    region: "Asia Pacific",
    city: "Ulaanbaatar",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "mn1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.82.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Montenegro",
    region: "Europe",
    city: "Podgorica",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "me1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.83.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Morocco",
    region: "Africa the Middle East and India",
    city: "Rabat",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ma1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.197.76.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Myanmar",
    region: "Asia Pacific",
    city: "Naypyidaw",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "mm1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.197.77.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Nepal",
    region: "Asia Pacific",
    city: "Kathmandu",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "np1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.197.78.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Netherlands",
    region: "Europe",
    city: "Amsterdam",
    categories: ["Onion Over VPN"],
    number: 6,
    hostname: "nl-onion6.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["213.232.87.219"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "New Zealand",
    region: "Asia Pacific",
    city: "Auckland",
    categories: ["Standard VPN servers", "P2P"],
    number: 86,
    hostname: "nz86.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["116.90.74.67"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Nigeria",
    region: "Africa the Middle East and India",
    city: "Lagos",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ng1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.197.79.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "North Macedonia",
    region: "Europe",
    city: "Skopje",
    categories: ["Standard VPN servers"],
    number: 11,
    hostname: "mk11.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.225.28.163"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Norway",
    region: "Europe",
    city: "Oslo",
    categories: ["Standard VPN servers", "P2P"],
    number: 141,
    hostname: "no141.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.203.163"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Pakistan",
    region: "Asia Pacific",
    city: "Karachi",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "pk1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.239.148.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Panama",
    region: "The Americas",
    city: "Panama City",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "pa1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.239.149.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Papua New Guinea",
    region: "Asia Pacific",
    city: "Port Moresby",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "pg1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.67.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Paraguay",
    region: "The Americas",
    city: "Asunción",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "py1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.239.150.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Peru",
    region: "The Americas",
    city: "Lima",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "pe1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.239.151.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Philippines",
    region: "Asia Pacific",
    city: "Manila",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ph1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.71.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Poland",
    region: "Europe",
    city: "Warsaw",
    categories: ["Standard VPN servers", "P2P"],
    number: 122,
    hostname: "pl122.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.211.171"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Portugal",
    region: "Europe",
    city: "Lisbon",
    categories: ["Standard VPN servers", "P2P"],
    number: 66,
    hostname: "pt66.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["91.205.230.193"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Puerto Rico",
    region: "The Americas",
    city: "San Juan",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "pr1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.76.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Romania",
    region: "Europe",
    city: "Bucharest",
    categories: ["Standard VPN servers", "P2P"],
    number: 59,
    hostname: "ro59.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["86.106.137.187"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Serbia",
    region: "Europe",
    city: "Belgrade",
    categories: ["Standard VPN servers", "P2P"],
    number: 48,
    hostname: "rs48.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["141.98.103.123"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Singapore",
    region: "Asia Pacific",
    city: "Singapore",
    categories: ["Standard VPN servers", "P2P"],
    number: 455,
    hostname: "sg455.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["103.107.198.131"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Slovakia",
    region: "Europe",
    city: "Bratislava",
    categories: ["Standard VPN servers", "P2P"],
    number: 40,
    hostname: "sk40.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.245.85.75"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Slovenia",
    region: "Europe",
    city: "Ljubljana",
    categories: ["Standard VPN servers", "P2P"],
    number: 14,
    hostname: "si14.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["195.158.249.168"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "South Africa",
    region: "Africa the Middle East and India",
    city: "Johannesburg",
    categories: ["Standard VPN servers", "P2P"],
    number: 128,
    hostname: "za128.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.203.122.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "South Korea",
    region: "Asia Pacific",
    city: "Seoul",
    categories: ["Standard VPN servers"],
    number: 31,
    hostname: "kr31.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["210.217.18.72"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Spain",
    region: "Europe",
    city: "Barcelona",
    categories: ["Standard VPN servers", "P2P"],
    number: 220,
    hostname: "es220.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.214.97.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Spain",
    region: "Europe",
    city: "Madrid",
    categories: ["Standard VPN servers", "P2P"],
    number: 114,
    hostname: "es114.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.199.243"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Sri Lanka",
    region: "Asia Pacific",
    city: "Colombo",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "lk1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.77.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Sweden",
    region: "Europe",
    city: "Stockholm",
    categories: ["Double VPN"],
    number: 10,
    hostname: "nl-se10.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["194.127.173.34"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Switzerland",
    region: "Europe",
    city: "Zurich",
    categories: ["Onion Over VPN"],
    number: 2,
    hostname: "ch-onion2.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.120.137.172"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Taiwan",
    region: "Asia Pacific",
    city: "Taipei",
    categories: ["Double VPN"],
    number: 3,
    hostname: "hk-tw3.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["84.17.37.79"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Thailand",
    region: "Asia Pacific",
    city: "Bangkok",
    categories: ["Standard VPN servers"],
    number: 14,
    hostname: "th14.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["122.155.174.64"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Trinidad and Tobago",
    region: "The Americas",
    city: "Port of Spain",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "tt1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.78.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Turkey",
    region: "Africa the Middle East and India",
    city: "Istanbul",
    categories: ["Standard VPN servers", "P2P"],
    number: 51,
    hostname: "tr51.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["87.249.139.62"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Ukraine",
    region: "Europe",
    city: "Kyiv",
    categories: ["Standard VPN servers", "P2P"],
    number: 51,
    hostname: "ua51.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.19.218.139"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United Arab Emirates",
    region: "Africa the Middle East and India",
    city: "Dubai",
    categories: ["Standard VPN servers", "P2P"],
    number: 54,
    hostname: "ae54.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["146.70.238.3"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United Kingdom",
    region: "Europe",
    city: "Edinburgh",
    categories: ["Standard VPN servers", "P2P"],
    number: 2432,
    hostname: "uk2432.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["188.212.154.38"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United Kingdom",
    region: "Europe",
    city: "Glasgow",
    categories: ["Standard VPN servers", "P2P"],
    number: 2470,
    hostname: "uk2470.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["188.241.157.38"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United Kingdom",
    region: "Europe",
    city: "London",
    categories: ["Double VPN"],
    number: 10,
    hostname: "fr-uk10.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["138.199.47.180"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United Kingdom",
    region: "Europe",
    city: "Manchester",
    categories: ["Standard VPN servers", "P2P"],
    number: 1689,
    hostname: "uk1689.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["152.89.207.2"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "Europe",
    city: "New York",
    categories: ["Dedicated IP"],
    number: 10562,
    hostname: "us10562.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["138.199.11.150"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Atlanta",
    categories: ["Standard VPN servers", "P2P"],
    number: 5109,
    hostname: "us5109.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.93.0.98"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Buffalo",
    categories: ["Dedicated IP"],
    number: 2920,
    hostname: "us2920.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["96.9.246.179"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Charlotte",
    categories: ["Standard VPN servers", "P2P"],
    number: 8474,
    hostname: "us8474.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["192.145.117.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Chicago",
    categories: ["Standard VPN servers", "P2P"],
    number: 6301,
    hostname: "us6301.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["172.93.177.235"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Dallas",
    categories: ["Dedicated IP"],
    number: 2943,
    hostname: "us2943.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["89.187.175.97"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Denver",
    categories: ["Standard VPN servers", "P2P"],
    number: 5066,
    hostname: "us5066.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.102.45.2"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Kansas City",
    categories: ["Standard VPN servers", "P2P"],
    number: 9573,
    hostname: "us9573.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.229.59.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Los Angeles",
    categories: ["Dedicated IP"],
    number: 2945,
    hostname: "us2945.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["89.187.185.86"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Manassas",
    categories: ["Double VPN"],
    number: 75,
    hostname: "ca-us75.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["37.19.212.207"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Miami",
    categories: ["Standard VPN servers", "P2P"],
    number: 5351,
    hostname: "us5351.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.245.86.235"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Phoenix",
    categories: ["Standard VPN servers", "P2P"],
    number: 8698,
    hostname: "us8698.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["192.145.119.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Saint Louis",
    categories: ["Standard VPN servers", "P2P"],
    number: 10317,
    hostname: "us10317.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["185.172.52.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Salt Lake City",
    categories: ["Standard VPN servers", "P2P"],
    number: 10414,
    hostname: "us10414.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["31.222.254.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "San Francisco",
    categories: ["Standard VPN servers", "P2P"],
    number: 8510,
    hostname: "us8510.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["192.145.118.100"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "United States",
    region: "The Americas",
    city: "Seattle",
    categories: ["Standard VPN servers", "P2P"],
    number: 5086,
    hostname: "us5086.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["84.17.41.130"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Uruguay",
    region: "The Americas",
    city: "Montevideo",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "uy1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["82.149.79.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Uzbekistan",
    region: "Asia Pacific",
    city: "Tashkent",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "uz1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.64.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Venezuela",
    region: "The Americas",
    city: "Caracas",
    categories: ["Standard VPN servers", "P2P"],
    number: 1,
    hostname: "ve1.nordvpn.com",
    tcp: true,
    udp: true,
    ips: ["212.97.65.1"],
  },
  {
    vpn: "openvpn",
    vpnType: "nord",
    country: "Vietnam",
    region: "Asia Pacific",
    city: "Hanoi",
    categories: ["Standard VPN servers"],
    number: 18,
    hostname: "vn18.nordvpn.com",
    tcp: true,
    ips: ["125.212.220.51"],
  },
];
